server:
  port: 8762

---

spring:
  security:  # 安全认证
    user:
      name: admin
      password: 123456
  application:
    name: yls_spring_cloud_eureka_server #项目名称

---

eureka:
  instance:
    hostname: yls002
    instance-id:  ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  server:
    enable-self-preservation: true # 关闭安全模式
  client:
    ## 是否把自己注册到 Eureka Server，默认为 true。由于当前为Eureka Server,故设为 false
    register-with-eureka: false
    ## 是否从 Eureka Server中获取注册信息，默认为 true，由于这是一个单一的 Eureka Server，不需同步数据，故设置为 false
    fetch-registry: false
    service-url:
      ## 设置与 Eureka Server的交互地址，多个地址可以用 逗号（,）分割
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@yls001:8671/eureka/
#      defaultZone: http://localhost:8761/eureka/




