server:
  port: 8881

---

spring:
  application:
    name: yls-cloud-nacos-config

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
      discovery:
        server-addr: 127.0.0.1:8848


