# 数据源的相关配置
spring:
  #jpa的配置：这里主要是配置一个主数据源
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  #数据源配置：druid的配置，结合mysql配置
  datasource:
    primary:
      #数据连接类型、数据库连接信息：用户名、密码
      db-type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/yls_privilege_management?userUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
      #高版本采用com.mysql.cj.jdbc.Driver
      #driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      #数据连接类型、数据库连接信息：用户名、密码
      db-type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/yls_privilege_log?userUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
      #高版本采用com.mysql.cj.jdbc.Driver
      #driver-class-name: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      #初始化大小、最小、最大
      initial-size: 1
      min-idle: 1
      max-active: 50
      #配置获取连接等待超时时间，单位是毫秒
      max-wait: 10000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 10000
      #配置一个连接在池中最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCase，并且指定每个连接上PSCase的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      #配置监控统计拦截的filters，去掉后监控页面的sql无法统计，‘wall’用于防火墙
      #filters: stat,wall,log4j
      filters: stat
      #打开mergeSQL功能，慢sql查询
      #active-connections: druid.stat.mergeSql=true
      filter:
        stat:
          slow-sql-millis: 5000
      #合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
    ##项目启动时创建数据库表的SQL脚本
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql

  ## 批处理
  batch:
    ## 当项目启动时就会执行配置好的批处理操作
    initialize-schema: always
    ## 禁止Spring Batch自动执行
    job:
      enabled: false
