###应用监控的配置
management:
  endpoints:
    web:
      # 设置监控访问的应用路径，默认是/actuator
      # base-path: /moitor
      exposure:
        # 暴露监控访问接口，默认是/health和info
        include: "*"
        # 显示屏蔽监控访问接口
        exclude: env,metrics
  # 开放关闭应用程序端点，不建议开启
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  ## 配置显示git的提交信息
  info:
    git:
      mode: full

## 自定义信息： 将在info端点显示
info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
  author:
    name: yls
    email: 268962@qq.com

## Knife4j 接口文档
knife4j:
  basic:
    username: admin
    password: admin
    enable: true #开启认证
  production: false #默认是false ,屏蔽所有Swagger的相关资源
  enable: true  #是否开启swagger
