####redis cluster的客户端lettuce
#spring:
#   redis:
#      cluster:
#         nodes:
#            - 192.168.133.104:6379
#            - 192.168.133.104:6380
#            - 192.168.133.105:6379
#            - 192.168.133.105:6380
#            - 192.168.133.106:6379
#            - 192.168.133.106:6380
#   lettuce:
#      pool:
#         #最大活跃连接数 ：（默认8）
#         max-active: 5
#         #最大空闲连接数：（默认8）
#         max-idle: 10
#         #最小空闲连接数：（默认0）
#         min-idle: 0
#         #连接池最大阻塞等待时间（使用负值表示没有限制）
#         max-wait: 6000
#      timeout: 6000

##redis 单机版客户端
spring:
   redis:
      # 地址
      host: 127.0.0.1
      # 端口
      port: 6379
      #密码
#      password: shj357yui
      # 超时时间
      timeout: 6000
      lettuce:
         pool:
            #最大活跃连接数 ：（默认8）
            max-active: 10
            #最大空闲连接数：（默认8）
            max-idle: 10
            #最小空闲连接数：（默认0）
            min-idle: 0
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: 6000
      #使用的Redis库的编号，Redis中提供了16个database,编号为0~15
#      database: 0
