###程序的端口
server:
  port: 8443
  ## tomcat的相关配置
  tomcat:
    max-connections: 10000
    max-threads: 500
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 30m
  ## https证书配置
#  ssl:
#    key-store: sang.p12
#    key-alias: tomcathttps
#    key-store-password: 123456


###分开设置配置文件
spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false #页面不加载缓存，修改即时生效
  profiles:
    active: datasource,thymeleaf,actuator,fileupload,elasticsearch #激活的配置文件
    #定义项目的静态资源 ：
    #默认位置： classpath:/META-INF/resources/
  #resources:
    #static-locations: classpath:/static/
  #定义项目的静态资源
  #mvc:
   # static-path-pattern: /static/**
  #spring-boot-admin-starter-client 监控客户端的相关配置
  boot:
    admin:
      client:
        # 服务端的请求地址
        url: http://localhost:8081
        username: admin
        password: 123456
        instance:
          service-base-url: http://localhost:8443

  application:
    name: yls_privilege_manager




  ##注冊服務
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}
      host: localhost
      port: 8500


##日志服务器
logging:
  config: classpath:logback-spring.xml

## mybatis
mybatis:
  mapper-locations: classpath*:mappers/*.xml
#  type-aliases-package: com.authority.manager.web.model
  configuration:
    # 当没有为参数提供特定的 JDBC 类型时，为空值指定 JDBC 类型。
    # oracle 数据库建议配置为 JdbcType.NULL, 默认是 Other
    jdbc-type-for-null: 'null'
    # 是否打印 sql 语句 调试的时候可以开启
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


