server:
  port: 8761

---

spring:
  security:  # 安全认证
    user:
      name: admin
      password: 123456
  application:
    name: yls_spring_cloud_eureka_server #项目名称

---

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true # 关闭安全模式
  client:
    ## 是否把自己注册到 Eureka Server，默认为 true。由于当前为Eureka Server,故设为 false
    register-with-eureka: false
    ## 是否从 Eureka Server中获取注册信息，默认为 true，由于这是一个单一的 Eureka Server，不需同步数据，故设置为 false
    fetch-registry: false
    service-url:
      ## 设置与 Eureka Server的交互地址，多个地址可以用 逗号（,）分割
      default-zone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
#      default-zone: http://localhost:8761/eureka/



